[pdf_report]
title = "Протокол испытаний беспилотной авиационной системы"
organization = "ООО «С.И.Т»"
license_number = "1234567"
address = "планета Земля"
test_type = "Ручное испытание"
operator_name = "Боровой Арсентий"
comment = "Испытание прошло штатно"
conclusion = "Воздушное средство пригодно к эксплуатации"
result = "_________"

